name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '13', '15' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.Java }}
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Store result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: target-${{ matrix.Java }}-jar
          path: target/*.jar
